#!/bin/bash

rootdir=/Applications/SubutaiP2P.app

echo "New installation log" > /tmp/p2p-install.log

if [ ! -d "$rootdir" ]; then
    echo "$rootdir doesn't exists"  >> /tmp/p2p-install.log
    exit 100
fi

if [ ! -e "$rootdir/Contents/MacOS/SubutaiP2P" ]; then
    echo "$rootdir/Contents/MacOS/SubutaiP2P doesn't exists"
    exit 101
fi

chmod +x $rootdir/Contents/MacOS/SubutaiP2P
if [ -L "/usr/local/bin/p2p" ]; then
	rm -f /usr/local/bin/p2p
fi
mkdir -p /usr/local/bin
ln -s $rootdir/Contents/MacOS/SubutaiP2P /usr/local/bin/p2p

mkdir -p /tmp/subutai
curl -k -o /tmp/subutai/tuntap.pkg https://cdn.subutai.io:8338/kurjun/rest/raw/get\?name=tuntap_20150118_osx.pkg
installer -pkg /tmp/subutai/tuntap.pkg -target /

mkdir -p /usr/local/etc/p2p
echo 'iptool: /sbin/ifconfig' > /usr/local/etc/p2p/config.yaml

chown -R $USER $rootdir
chown -R $USER /usr/local/bin/p2p

if [ -e /Library/LaunchDaemons/io.subutai.p2p.daemon.plist ]; then
    launchctl unload /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
fi

#cp $rootdir/Library/LaunchDaemons/io.subutai.p2p.daemon.plist /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
#cp $rootdir/etc/newsyslog.d/p2p.conf /etc/newsyslog.d/p2p.conf
chmod 0555 /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
chown root:wheel /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
chown root:wheel /etc/newsyslog.d/p2p.conf
launchctl load /Library/LaunchDaemons/io.subutai.p2p.daemon.plist
